all: deletion insertion linear_search traverse

binary_search: binary_search.c
	gcc binary_search.c -o ./bin/binary_search

deletion: deletion.c
	gcc deletion.c -o ./bin/deletion

insertion: insertion.c
	gcc insertion.c -o ./bin/insertion 

linear_search: linear_search.c
	gcc linear_search.c -o ./bin/linear_search

traverse: traverse.c
	gcc traverse.c -o ./bin/traverse

clean:
	rm -rf ./bin
	mkdir bin
